spring:
  datasource:
    url: jdbc:postgresql://localhost:5432
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: none

  messages:
    basename: message
    encoding: UTF-8
    fallback-to-system-locale=: true

logging:
  level:
    org:
      springframework: info

springdoc:
  swagger:
    ui:
      path: /swagger-ui.html

application:
  core:
    env: "build"
    version: "@project.version@"
  documentation:
    server:
      url: