#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: jhub
#    password: pass
application:
  core:
    env: "local_dev"
  documentation:
    server:
      url: http://localhost:8080
  sse:
    min-duration: "PT1D"
    min-frequency: "PT0.001S"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true