on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to digital ocean
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.DIGITAL_OCEAN_HOST }} >> ~/.ssh/known_hosts
          scp $PACKAGE_URL $SSH_USER@$SSH_HOST:$DEPLOY_URL
        shell: bash
        env:
          SSH_USER: ${{ secrets.DIGITAL_OCEAN_USER }}
          SSH_HOST: ${{ secrets.DIGITAL_OCEAN_HOST }}
          PACKAGE_URL: ${{ github.workspace }}/target/*.jar
          DEPLOY_URL: ${{ secrets.CLOUD_DEPLOY_URL }}/target/*.jar

      - name: Run remote script
        run: |
          ssh ${{ secrets.DIGITAL_OCEAN_USER }}@${{ secrets.DIGITAL_OCEAN_HOST }} \
          "/home/jhub/test.sh"
